FROM mcr.microsoft.com/devcontainers/python:3.14-trixie

# Instale as bibliotecas necessárias
RUN pip install --no-cache-dir \
    pandas \
    numpy \
    matplotlib \
    jupyter \
    luigi \
    pyarrow \
    google-genai

